-- 12_q06_gmv_concentration_by_category.sql
/*
Purpose:
 Analyse GMV concentration by product category to identify which categories
 contribute the largest share of marketplace transaction value.

Grain:
 One row per product_category_english.

Primary inputs:
 fact_order_items_clean

Business definitions:
 category_gmv = total item_gmv generated by the category
 category_gmv_share = category_gmv / total marketplace GMV
 cumulative_gmv_share = running total of category GMV share after sorting descending
 order_items = total included item rows in the category
 orders_containing_category = distinct orders containing at least one item from the category

Key assumptions / caveats:
 Category analysis is performed at item grain because category is an item-level attribute.
 Cancelled and unavailable orders are excluded.
 GMV is transaction value, not audited revenue or margin.
*/

WITH category_gmv AS (
    SELECT
        product_category_english,
        ROUND(SUM(item_gmv), 2) AS category_gmv,
        COUNT(*) AS order_items,
        COUNT(DISTINCT order_id) AS orders_containing_category
    FROM fact_order_items_clean
    WHERE order_status NOT IN ('canceled', 'unavailable')
      AND item_gmv IS NOT NULL
    GROUP BY
        product_category_english
),
category_gmv_with_share AS (
    SELECT
        product_category_english,
        category_gmv,
        order_items,
        orders_containing_category,
        ROUND(
            category_gmv / SUM(category_gmv) OVER (),
            4
        ) AS category_gmv_share
    FROM category_gmv
),
ranked_categories AS (
    SELECT
        product_category_english,
        category_gmv,
        order_items,
        orders_containing_category,
        category_gmv_share,
        ROUND(
            SUM(category_gmv_share) OVER (
                ORDER BY category_gmv DESC
                ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
            ),
            4
        ) AS cumulative_gmv_share,
        RANK() OVER (
            ORDER BY category_gmv DESC
        ) AS gmv_rank
    FROM category_gmv_with_share
)
SELECT
    product_category_english,
    category_gmv,
    category_gmv_share,
    cumulative_gmv_share,
    order_items,
    orders_containing_category,
    gmv_rank
FROM ranked_categories
ORDER BY
    category_gmv DESC;

--validation step
--manually validate result of a top category
SELECT
    ROUND(SUM(item_gmv), 2) AS category_gmv,
    COUNT(*) AS order_items,
    COUNT(DISTINCT order_id) AS orders_containing_category
FROM fact_order_items_clean
WHERE order_status NOT IN ('canceled', 'unavailable')
  AND item_gmv IS NOT NULL
  AND product_category_english = 'health_beauty';


/*GMV is concentrated in a relatively small set of categories. Health_beauty, watches_gifts,
 bed_bath_table, sports_leisure, and computers_accessories together account for 39.17% of 
 marketplace GMV. By the top 10 categories, cumulative GMV share rises to 62.34%, and by 
 the top 15 it exceeds 76%.

This suggests that marketplace commercial performance is driven disproportionately by a 
limited number of product groups rather than being evenly spread across the catalogue. 
From a business-risk perspective, that concentration increases dependency on the continued 
performance of a small core of categories.*/