-- Q-06 GMV concentration by business segment
/*
Purpose:
 Analyse GMV concentration by business segment to identify which broader
 product segments contribute the largest share of marketplace transaction value.

Grain:
 One row per business_segment.

Primary inputs:
 fact_order_items_clean
 category_mapping

Business definitions:
 segment_gmv = total item_gmv generated by the segment
 segment_gmv_share = segment_gmv / total marketplace GMV
 cumulative_gmv_share = running total of segment GMV share after sorting descending
 order_items = total included item rows in the segment
 orders_containing_segment = distinct orders containing at least one item from the segment

Key assumptions / caveats:
 Segment analysis is performed at item grain because category is an item-level attribute.
 Raw categories are rolled up using analyst-defined business segments from category_mapping.
 Cancelled and unavailable orders are excluded.
 GMV is transaction value, not audited revenue or margin.

Data quality note:
 The Olist category labels include source spelling inconsistencies such as
 'costruction_tools_garden' and 'costruction_tools_tools'. These raw keys are
 preserved exactly in category_mapping to maintain join integrity.
*/

WITH segment_gmv AS (
    SELECT
        cm.business_segment,
        ROUND(SUM(foi.item_gmv)::numeric, 2) AS segment_gmv,
        COUNT(*) AS order_items,
        COUNT(DISTINCT foi.order_id) AS orders_containing_segment
    FROM fact_order_items_clean AS foi
    LEFT JOIN category_mapping AS cm
        ON foi.product_category_english = cm.product_category_english
    WHERE foi.order_status NOT IN ('canceled', 'unavailable')
      AND foi.item_gmv IS NOT NULL
    GROUP BY
        cm.business_segment
),
segment_gmv_with_share AS (
    SELECT
        business_segment,
        segment_gmv,
        order_items,
        orders_containing_segment,
        ROUND(
            segment_gmv / SUM(segment_gmv) OVER (),
            4
        ) AS segment_gmv_share
    FROM segment_gmv
),
ranked_segments AS (
    SELECT
        business_segment,
        segment_gmv,
        order_items,
        orders_containing_segment,
        segment_gmv_share,
        ROUND(
            SUM(segment_gmv_share) OVER (
                ORDER BY segment_gmv DESC
                ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
            ),
            4
        ) AS cumulative_gmv_share,
        RANK() OVER (
            ORDER BY segment_gmv DESC
        ) AS gmv_rank
    FROM segment_gmv_with_share
)
SELECT
    business_segment,
    segment_gmv,
    segment_gmv_share,
    cumulative_gmv_share,
    order_items,
    orders_containing_segment,
    gmv_rank
FROM ranked_segments
ORDER BY
    segment_gmv DESC;

-- Q-06 Support: GMV concentration by raw category
/*
Purpose:
 Provide category-level drilldown behind the business-segment GMV view.
 This helps identify which raw categories are driving the largest segment-level
 concentration patterns.

Grain:
 One row per product_category_english.
*/

WITH category_gmv AS (
    SELECT
        foi.product_category_english,
        cm.business_segment,
        ROUND(SUM(foi.item_gmv)::numeric, 2) AS category_gmv,
        COUNT(*) AS order_items,
        COUNT(DISTINCT foi.order_id) AS orders_containing_category
    FROM fact_order_items_clean AS foi
    LEFT JOIN category_mapping AS cm
        ON foi.product_category_english = cm.product_category_english
    WHERE foi.order_status NOT IN ('canceled', 'unavailable')
      AND foi.item_gmv IS NOT NULL
    GROUP BY
        foi.product_category_english,
        cm.business_segment
),
category_gmv_with_share AS (
    SELECT
        product_category_english,
        business_segment,
        category_gmv,
        order_items,
        orders_containing_category,
        ROUND(
            category_gmv / SUM(category_gmv) OVER (),
            4
        ) AS category_gmv_share
    FROM category_gmv
),
ranked_categories AS (
    SELECT
        product_category_english,
        business_segment,
        category_gmv,
        order_items,
        orders_containing_category,
        category_gmv_share,
        ROUND(
            SUM(category_gmv_share) OVER (
                ORDER BY category_gmv DESC
                ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
            ),
            4
        ) AS cumulative_gmv_share,
        RANK() OVER (
            ORDER BY category_gmv DESC
        ) AS gmv_rank
    FROM category_gmv_with_share
)
SELECT
    product_category_english,
    business_segment,
    category_gmv,
    category_gmv_share,
    cumulative_gmv_share,
    order_items,
    orders_containing_category,
    gmv_rank
FROM ranked_categories
ORDER BY
    category_gmv DESC;

/*
Business interpretation:
GMV is concentrated across a small number of broad business segments.
Home & Living is the largest segment, accounting for 27.13% of marketplace GMV,
followed by Leisure, Gifts & Hobbies at 17.53% and Beauty, Health & Baby at 15.05%.
Together, the top three segments contribute 59.71% of total GMV, and the top four
segments contribute 73.63%.

This suggests that marketplace commercial performance depends heavily on a limited
set of product segments rather than being evenly distributed across the catalogue.
The raw category drilldown remains useful for identifying which categories drive
each segment, but the segment view provides the cleaner business-level concentration
story.
*/


