-- 14_q08_average_basket_size_and_gmv_by_state.sql
/*
Purpose:
 Analyse basket size and GMV by customer state to identify geographies
 with higher-value demand.

Grain:
 One row per customer_state.

Primary inputs:
 fact_orders_clean

Business definitions:
 total_orders = total included orders in the state
 total_gmv = total GMV generated by the state
 avg_order_value = average order GMV in the state
 avg_items_per_order = average number of items per order in the state

Key assumptions / caveats:
 Analysis is performed at order grain using fact_orders_clean.
 Canceled and unavailable orders are excluded.
 Rows with null order_gmv are excluded.
 Higher total GMV may reflect order volume, while higher avg_order_value
 and avg_items_per_order reflect stronger basket value/intensity.
*/

SELECT
    customer_state,
    COUNT(*) AS total_orders,
    ROUND(SUM(order_gmv), 2) AS total_gmv,
    ROUND(AVG(order_gmv), 2) AS avg_order_value,
    ROUND(AVG(total_items), 2) AS avg_items_per_order
FROM fact_orders_clean
WHERE order_status NOT IN ('canceled', 'unavailable')
  AND order_gmv IS NOT NULL
GROUP BY
    customer_state
ORDER BY
    total_gmv DESC;

--validation
SELECT
    COUNT(*) AS total_orders,
    ROUND(SUM(order_gmv), 2) AS total_gmv,
    ROUND(AVG(order_gmv), 2) AS avg_order_value,
    ROUND(AVG(total_items), 2) AS avg_items_per_order
FROM fact_orders_clean
WHERE order_status NOT IN ('canceled', 'unavailable')
  AND order_gmv IS NOT NULL
  AND customer_state = 'SP';

--high value demand ranking 
WITH state_metrics AS (
    SELECT
        customer_state,
        COUNT(*) AS total_orders,
        ROUND(SUM(order_gmv), 2) AS total_gmv,
        ROUND(AVG(order_gmv), 2) AS avg_order_value,
        ROUND(AVG(total_items), 2) AS avg_items_per_order
    FROM fact_orders_clean
    WHERE order_status NOT IN ('canceled', 'unavailable')
      AND order_gmv IS NOT NULL
    GROUP BY
        customer_state
)
SELECT
    customer_state,
    total_orders,
    total_gmv,
    avg_order_value,
    avg_items_per_order
FROM state_metrics
WHERE total_orders >= 300
ORDER BY
    avg_order_value DESC,
    total_orders DESC;