-- 14_q08_average_basket_size_and_gmv_by_state.sql
/*
Purpose:
 Analyse basket size and GMV by customer state to identify geographies
 with higher-value demand.

Grain:
 One row per customer_state.

Primary inputs:
 fact_orders_clean

Business definitions:
 total_orders = total included orders in the state
 total_gmv = total GMV generated by the state
 avg_order_value = average order GMV in the state
 avg_items_per_order = average number of items per order in the state

Key assumptions / caveats:
 Analysis is performed at order grain using fact_orders_clean.
 Canceled and unavailable orders are excluded.
 Rows with null order_gmv are excluded.
 Higher total GMV may reflect order volume, while higher avg_order_value
 and avg_items_per_order reflect stronger basket value/intensity.
*/

SELECT
    customer_state,
    COUNT(*) AS total_orders,
    ROUND(SUM(order_gmv), 2) AS total_gmv,
    ROUND(AVG(order_gmv), 2) AS avg_order_value,
    ROUND(AVG(total_items), 2) AS avg_items_per_order
FROM fact_orders_clean
WHERE order_status NOT IN ('canceled', 'unavailable')
  AND order_gmv IS NOT NULL
GROUP BY
    customer_state
ORDER BY
    total_gmv DESC;

--validation
SELECT
    COUNT(*) AS total_orders,
    ROUND(SUM(order_gmv), 2) AS total_gmv,
    ROUND(AVG(order_gmv), 2) AS avg_order_value,
    ROUND(AVG(total_items), 2) AS avg_items_per_order
FROM fact_orders_clean
WHERE order_status NOT IN ('canceled', 'unavailable')
  AND order_gmv IS NOT NULL
  AND customer_state = 'SP';

--high value demand ranking 
WITH state_metrics AS (
    SELECT
        customer_state,
        COUNT(*) AS total_orders,
        ROUND(SUM(order_gmv), 2) AS total_gmv,
        ROUND(AVG(order_gmv), 2) AS avg_order_value,
        ROUND(AVG(total_items), 2) AS avg_items_per_order
    FROM fact_orders_clean
    WHERE order_status NOT IN ('canceled', 'unavailable')
      AND order_gmv IS NOT NULL
    GROUP BY
        customer_state
)
SELECT
    customer_state,
    total_orders,
    total_gmv,
    avg_order_value,
    avg_items_per_order
FROM state_metrics
WHERE total_orders >= 300
ORDER BY
    avg_order_value DESC,
    total_orders DESC;


-- Q-08 Support: Average basket size and GMV by customer region
/*
Purpose:
 Roll customer-state basket and GMV analysis up to region level using
 brazil_state_reference. This helps show whether high-value demand patterns
 cluster geographically beyond individual state codes.

Grain:
 One row per customer region.

Primary inputs:
 fact_orders_clean
 brazil_state_reference

Business definitions:
 total_orders = count of included non-cancelled, non-unavailable orders
 total_gmv = total order_gmv generated by customers in the region
 avg_order_value = average GMV per order
 avg_items_per_order = average number of items per order

Key assumptions / caveats:
 Cancelled and unavailable orders are excluded.
 Orders with null order_gmv are excluded.
 Region is based on customer_state, so this is demand-side geography,
 not seller-side geography.
 GMV is transaction value, not audited revenue or margin.
*/

WITH region_basket_metrics AS (
    SELECT
        bsr.region,
        COUNT(*) AS total_orders,
        ROUND(SUM(foc.order_gmv)::numeric, 2) AS total_gmv,
        ROUND(AVG(foc.order_gmv)::numeric, 2) AS avg_order_value,
        ROUND(AVG(foc.total_items)::numeric, 2) AS avg_items_per_order
    FROM fact_orders_clean AS foc
    LEFT JOIN brazil_state_reference AS bsr
        ON foc.customer_state = bsr.state_code
    WHERE foc.order_status NOT IN ('canceled', 'unavailable')
      AND foc.order_gmv IS NOT NULL
    GROUP BY
        bsr.region
)
SELECT
    region,
    total_orders,
    total_gmv,
    avg_order_value,
    avg_items_per_order
FROM region_basket_metrics
ORDER BY
    total_gmv DESC;