/*
Q-10 Revenue concentration by seller

Business question:
What share of total GMV is generated by the top 10% and top 20% of sellers?

Important logic:
Aggregate to seller grain first, then rank sellers by seller_gmv.
Do not use review filters from Q-09.
*/

WITH seller_gmv AS (
    SELECT
        seller_id,
        MAX(seller_state) AS seller_state,
        COUNT(DISTINCT order_id) AS orders_containing_seller,
        SUM(item_gmv) AS seller_gmv
    FROM fact_order_items_clean
    WHERE order_status NOT IN ('canceled', 'unavailable')
      AND item_gmv IS NOT NULL
    GROUP BY
        seller_id
),
seller_ranked AS (
    SELECT
        seller_id,
        seller_state,
        orders_containing_seller,
        seller_gmv,
        ROW_NUMBER() OVER (ORDER BY seller_gmv DESC) AS seller_rank,
        COUNT(*) OVER () AS total_sellers,
        SUM(seller_gmv) OVER () AS total_gmv
    FROM seller_gmv
),
seller_cutoffs AS (
    SELECT
        *,
        CEIL(total_sellers * 0.10) AS top_10_seller_cutoff,
        CEIL(total_sellers * 0.20) AS top_20_seller_cutoff
    FROM seller_ranked
)
SELECT
    MAX(total_sellers) AS total_sellers,
    MAX(top_10_seller_cutoff) AS top_10_seller_count,
    ROUND(
        SUM(CASE WHEN seller_rank <= top_10_seller_cutoff THEN seller_gmv ELSE 0 END)::numeric,
        2
    ) AS top_10_gmv,
    ROUND(
        100.0 * SUM(CASE WHEN seller_rank <= top_10_seller_cutoff THEN seller_gmv ELSE 0 END)
        / MAX(total_gmv),
        2
    ) AS top_10_gmv_share_pct,
    MAX(top_20_seller_cutoff) AS top_20_seller_count,
    ROUND(
        SUM(CASE WHEN seller_rank <= top_20_seller_cutoff THEN seller_gmv ELSE 0 END)::numeric,
        2
    ) AS top_20_gmv,
    ROUND(
        100.0 * SUM(CASE WHEN seller_rank <= top_20_seller_cutoff THEN seller_gmv ELSE 0 END)
        / MAX(total_gmv),
        2
    ) AS top_20_gmv_share_pct,
    ROUND(MAX(total_gmv)::numeric, 2) AS total_marketplace_gmv
FROM seller_cutoffs;


--Q-10 Support: Cumulative GMV share by seller rank

WITH seller_gmv AS (
    SELECT
        seller_id,
        MAX(seller_state) AS seller_state,
        COUNT(DISTINCT order_id) AS orders_containing_seller,
        SUM(item_gmv) AS seller_gmv
    FROM fact_order_items_clean
    WHERE order_status NOT IN ('canceled', 'unavailable')
      AND item_gmv IS NOT NULL
    GROUP BY
        seller_id
),
seller_ranked AS (
    SELECT
        seller_id,
        seller_state,
        orders_containing_seller,
        seller_gmv,
        ROW_NUMBER() OVER (ORDER BY seller_gmv DESC) AS seller_rank,
        COUNT(*) OVER () AS total_sellers,
        SUM(seller_gmv) OVER () AS total_gmv,
        SUM(seller_gmv) OVER (
            ORDER BY seller_gmv DESC
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) AS cumulative_gmv
    FROM seller_gmv
)
SELECT
    seller_rank,
    seller_id,
    seller_state,
    orders_containing_seller,
    ROUND(seller_gmv::numeric, 2) AS seller_gmv,
    ROUND(100.0 * seller_gmv / total_gmv, 4) AS seller_gmv_share_pct,
    ROUND(100.0 * cumulative_gmv / total_gmv, 2) AS cumulative_gmv_share_pct
FROM seller_ranked
ORDER BY
    seller_rank
LIMIT 50;


/*For seller concentration, I aggregated item-level GMV to seller grain, ranked sellers by GMV, 
and measured how much marketplace value sat with the top seller cohorts. The results showed strong 
concentration: the top 10% of sellers generated 66.68% of total GMV, while the top 20% generated 81.93%. 
The remaining 80% of sellers contributed only 18.07% of GMV. The cumulative distribution showed that no 
single seller dominated the marketplace, but a relatively small top cohort carried a disproportionate share 
of commercial value. This suggests meaningful supply-side concentration risk, where performance issues or 
seller churn in the leading cohort could materially affect marketplace GMV. */